---
- name: Build and Push AWX
  hosts: localhost
  vars:
    source_repo: ansible/awx
    source_branch: devel
    # build image
    build_image_push: true
    build_image_registry: ""
    build_image_repo: ""
    build_image_tag: ""
    build_image: "{{ build_image_registry }}/{{ build_image_repo }}:{{ build_image_tag }}"
    # deploy to kubernetes
    deploy_namespace: ""
    deploy_domain: ""
    deploy: false
    prepare: false
    awx_namespace: "{{ deploy_namespace }}" 
    # awx-operator
    awx_operator_source_repo: "{{ source_repo }}"
    awx_operator_source_branch: "{{ source_branch }}"
    awx_operator_image_base: "{{ build_image_registry }}/{{ build_image_repo }}"
    awx_operator_image_tag: "{{ build_image_tag }}"
    # awx
    awx_name: awx
    awx_image: quay.io/ansible/awx
    awx_image_tag: latest
    awx_hostname: "{{ awx_name }}.{{ dns_domain }}"
    dns_domain: "{{ ansible_facts['nodename'] }}"
    create_awx: false 
    # notifications
    awx_url: ""
    slack_token: ""
    slack_notify: ""
#
  tasks:
  - name: Import prepare role
    ansible.builtin.import_role:
      name: prepare
    when: prepare | bool
#
  - name: Build AWX Operator Block
    block:
#      
      - name: Import build role
        ansible.builtin.import_role:
          name: build-awx-operator

      - name: Import create-awx role     
        ansible.builtin.import_role:
          name: create-awx
        when: create_awx | bool
        
    # rescue:
    # rescue tasks go here... (cleanup?)
    # error notifications and extra log output
    always:          
      - name: Send slack notification with AWX deployment info
        ignore_errors: yes
        slack:
          token: "{{ slack_token }}"
          color: good
          msg: |
            >*{{ awx_job_template_name }}*
            built from: *`{{ source_repo }}:{{ source_branch }}`*
            image: `{{ build_image }}`
            *AWX: https://{{ awx_hostname }}*

            *More details:*
            {{ awx_controller_url }}/#/jobs/playbook/{{ awx_job_id }}
            *_____________________________________________________*
        when: create_awx | bool and slack_notify | bool

      - name: Send slack notification for just an image build
        ignore_errors: yes
        slack:
          token: "{{ slack_token }}"
          color: good
          msg: |
            >*{{ awx_job_template_name }}*
            built from: *`{{ source_repo }}:{{ source_branch }}`*
            image: `{{ build_image }}`

            *More details:*
            {{ awx_controller_url }}/#/jobs/playbook/{{ awx_job_id }}
            *_____________________________________________________*
        when: not create_awx | bool and slack_notify | bool


# all the vars:
# awx_job_id: The Job ID for this job run
# {{ awx_job_id }}

# awx_job_launch_type: The description to indicate how the job was started:
# {{ awx_job_launch_type }}

# awx_job_template_id: The Job Template ID that this job run uses
# {{ awx_job_template_id }}

# awx_job_template_name: The Job Template name that this job uses
# {{ awx_job_template_name: }}

# awx_project_revision: The revision identifier for the source tree that this particular job uses (it is also the same as the job’s field scm_revision)
# {{ awx_project_revision }}

# awx_project_scm_branch: The configured default project SCM branch for the project the job template uses
# {{ awx_project_scm_branch }}

# awx_job_scm_branch If the SCM Branch is overwritten by the job, the value is shown here
# {{ awx_job_scm_branch }}

# awx_user_email: The user email of the controller user that started this job. This is not available for callback or scheduled jobs.
# {{ awx_user_email }}

# awx_user_name: The user name of the controller user that started this job. This is not available for callback or scheduled jobs.
# {{ awx_user_name }}

# awx_schedule_id: If applicable, the ID of the schedule that launched this job

# awx_schedule_name: If applicable, the name of the schedule that launched this job

# awx_workflow_job_id: If applicable, the ID of the workflow job that launched this job

# awx_workflow_job_name: If applicable, the name of the workflow job that launched this job. Note this is also the same as the workflow job template.

# awx_inventory_id: If applicable, the ID of the inventory this job uses
# {{ awx_inventory_id }}

# awx_inventory_name: If applicable, the name of the inventory this job uses
# {{ awx_inventory_name }}

