---
- name: Build and Push AWX
  hosts: localhost
  vars:
    source_repo: ansible/awx
    source_branch: devel
    # build image
    build_image_push: true
    build_image_registry: "ttl.sh"
    build_image_repo: ""
    build_image_tag: ""
    build_image: "{{ build_image_registry }}/{{ build_image_repo }}:{{ build_image_tag }}"
    # deploy to kubernetes
    deploy_namespace: ""
    deploy_domain: ""
    deploy: false
    prepare: false
    awx_namespace: "{{ deploy_namespace }}" 
    # awx-operator
    awx_operator_source_repo: "{{ source_repo }}"
    awx_operator_source_branch: "{{ source_branch }}"
    awx_operator_image_base: "{{ build_image_registry }}/{{ build_image_repo }}"
    awx_operator_image_tag: "{{ build_image_tag }}"
    # awx
    awx_name: awx
    awx_image: quay.io/ansible/awx
    awx_image_tag: latest
    awx_hostname: "{{ awx_name }}.{{ dns_domain }}"
    dns_domain: "{{ ansible_facts['nodename'] }}"
    create_awx: false 
#
  tasks:
  - name: Import prepare role
    ansible.builtin.import_role:
      name: prepare
    when: prepare | bool

  - name: Set awx name and namespaces to awx-{{ pr_sha[:7] }} for ci
    ansible.builtin.set_fact:
      awx_name: awx-{{ pr_sha[:7] }}
      awx_namespace: awx-{{ pr_sha[:7] }}
      deploy_namespace: awx-{{ pr_sha[:7] }}
    when: pr_sha != ""

  - name: Set awx deployment domain if defined
    ansible.builtin.set_fact:
      dns_domain: "{{ deploy_domain }}"
    when: deploy_domain != ""

    - name: Build AWX Operator Block
      block:
#      
        - name: Import build role
          ansible.builtin.import_role:
            name: build-awx-operator

        - name: Import create-awx role     
          ansible.builtin.import_role:
            name: create-awx
          when: create_awx | bool
          
#    rescue:
    # rescue tasks go here... (cleanup?)
    # error notifications and extra log output
#    always:          
    # notifications and logs and other stuff we want to always happen go here