---
# - name: Set message content
#   ansible.builtin.set_fact
#     github_comment: |
#       "{{ build_image }} successfully built and deployed."
- name: Comment test report to PR
  ignore_errors: true
  ansible.builtin.uri:
    url: "https://api.github.com/repos/{{ source_repo }}/issues/{{ pr_number }}/comments"
    method: POST
    body: "{{ build_image }} successfully built and deployed."
    status_code: 201
    body_format: json
    headers:
      Authorization: Bearer {{ github_token }}