---
- name: General Image Build Details
  ignore_errors: yes
  slack:
    token: "{{ slack_token }}"
    color: good
    parse: none
    msg: |
      >*{{ awx_job_template_name }}*
      build_image: `{{ build_image }}` `({{ ansible_facts['architecture']}})`
      build_source: `{{ source_repo }}:{{ source_branch }}`
      <{{ awx_controller_url }}/#/jobs/playbook/{{ awx_job_id }}|[ awx job #{{ awx_job_id }} ]>
  when: not create_awx and not deploy_awx

- name: Build AWX Operator and Create AWX
  ignore_errors: yes
  slack:
    token: "{{ slack_token }}"
    color: good
    parse: none
    msg: |
      >*{{ awx_job_template_name }}*
      build_image: `{{ build_image }}` `({{ ansible_facts['architecture']}})`
      build_source: `{{ source_repo }}:{{ source_branch }}`
      AWX: <https://{{ awx_hostname }}|https://{{ awx_hostname }}>
      AWX image: `{{ awx_image }}:{{ awx_image_tag }}`
      <{{ awx_controller_url }}/#/jobs/playbook/{{ awx_job_id }}|[ awx job #{{ awx_job_id }} ]>
  when: create_awx

- name: Build and Deploy AWX
  ignore_errors: yes
  slack:
    token: "{{ slack_token }}"
    color: good
    parse: none    
    msg: |
      >*{{ awx_job_template_name }}*
      build_image: `{{ build_image }}` `({{ ansible_facts['architecture']}})`
      build_source: `{{ source_repo }}:{{ source_branch }}`
      AWX: <https://{{ awx_hostname }}|https://{{ awx_hostname }}>
      AWX image: `{{ awx_image }}:{{ awx_image_tag }}`
      <{{ awx_controller_url }}/#/jobs/playbook/{{ awx_job_id }}|[ awx job #{{ awx_job_id }} ]>
  when: deploy_awx
